apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-pg-poc
  namespace: ms-pg-poc
data:
  application.yml: |-
    spring:
      application:
        name: ms-pg-poc
      datasource:
        hikari:
          connectionTimeout: 20000
          maximumPoolSize: 5
        url: jdbc:postgresql://dbsvc/odl
        username: hari
        password: postgres